version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./geektech/db.sqlite3:/geektech/db.sqlite3
      - ./geektech:/geektech
      - ./geektech/media:/geektech/media
    environment:
      - DEBUG=False
      - DJANGO_ALLOWED_HOSTS=158.160.39.142
    command: gunicorn --bind 0.0.0.0:8000 geektech.wsgi:application
