# Generated by Django 5.1.4 on 2024-12-24 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0002_promotions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Promotions',
            new_name='Promotion',
        ),
    ]
